/**
*    @author R.Hari Krishna
*    @date   22nd Jan 18
*    @description  Class for Constants                            
*     
*     Modification Log:
*------------------------------------------------------------------------------------
*       Developer             Date                Description
*------------------------------------------------------------------------------------
*       R.Hari Krishna       22nd Jan 18          Original Version
*/
@isTest
public class SRVS_Constants {   
    public static final String AGENT_PROFILE_NAME = 'Service Agent';
}